<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="azstorageexp" name="serviceTests.AddToCartTest" tests="8" failures="1" timestamp="16 Feb 2020 10:59:56 GMT" time="7.906" errors="0">
  <testcase name="oAuthTokenService" time="2.297" classname="serviceTests.AddToCartTest"/>
  <testcase name="signInUsingService" time="0.881" classname="serviceTests.AddToCartTest"/>
  <testcase name="searchSofaService" time="1.059" classname="serviceTests.AddToCartTest"/>
  <testcase name="getProductDetailsService" time="0.691" classname="serviceTests.AddToCartTest"/>
  <testcase name="addProductToCart" time="0.713" classname="serviceTests.AddToCartTest">
    <failure type="java.lang.AssertionError" message="expected [201] but found [409]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [409]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at services.cart.AddToCartRequest.verifyaddToCartResponseStatusCode(AddToCartRequest.java:33)
at serviceTests.AddToCartTest.addProductToCart(AddToCartTest.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- addProductToCart -->
  <testcase name="reviewCart" time="0.815" classname="serviceTests.AddToCartTest"/>
  <testcase name="updateCart" time="0.715" classname="serviceTests.AddToCartTest"/>
  <testcase name="deleteFromCart" time="0.735" classname="serviceTests.AddToCartTest"/>
</testsuite> <!-- serviceTests.AddToCartTest -->
